apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ .Values.job.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
{{ toYaml .Values.configmap.annotations | indent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
