{{- if .Values.dummy_service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "application.fullname" . }}"
  namespace: "{{ .Values.job.namespace }}"
  labels:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: runner
    job-name: "{{ template "application.fullname" . }}"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}