sealedSecret:
  enabled: false
job:
  enabled: true
  command:
  args:
  namespace: default
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  imagePullSecrets:
    name: image-registry-secret
configmap:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
image:
   repository: asia.gcr.io/systems-0001
   bucketName: sample_app
   path: ""
   tag: 1.0.0-c06e9200ec06e2b8f698840351d17429668fcf05
   pullPolicy: IfNotPresent
resources:
  limits:
   cpu: 4000m
   memory: 16Gi
  requests:
   cpu: 100m
   memory: 128Mi
# enable this dummy_service to prevent helm error 'no object visited'
# https://github.com/helm/helm/issues/4670#issuecomment-566525704
dummy_service:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
labels: {}
